# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b157a00dc6ea021b5deb9bdc212af1c69bf7ff3f24f724b7d0bff9590a7e0497ce28aecf0bde2a4390e0efea6d614326b9aed165deb53a9d919337fd4adc50d2

test:
  secret_key_base: c000d7a4f4cb7aee88fe4c959a90e88ee677d321ddafddd9ad037648f21e472ec03d5c5acb8346c8e4e21be92468056f9dd69889e2730444569de76a93d019c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
